version : "3.9"
name: project_docker

services:
  nginx:
    image: nginx:latest
    container_name: nginx-web-server
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ${NGINX_HTML_DIR}:/usr/share/nginx/html
      - ${NGINX_CONF_DIR}:/etc/nginx/conf.d/default.conf
      - nginx-logs:/var/log/nginx
    networks:
      - web-network
    restart: always
    depends_on:
      - mysql
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file: ./.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 30s
      timeout: 30s
      retries: 3
    labels:
      - "project=akso"
      - "service=webserver"
    deploy:
      resources:
        limits:
          cpus: "0.50"
          memory: 256M

  mysql:
    image: mysql:8.0
    container_name: mysql-database
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: datauser
      MYSQL_PASSWORD: mysqlpassword
      TZ: Asia/Jakarta
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql-backup:/backup
    networks:
      - web-network
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    env_file:
      - ./mysql/.env
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - "project=akso"
      - "service=database"
    configs:
      - source: mysql-config
        target: /etc/mysql/conf.d/custom.cnf
    deploy:
      resources:
        limits:
          cpus: "1.0"
          memory: 512M
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

networks:
  web-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450

volumes:
  nginx-logs:
    driver: local
  mysql-data:
    driver: local
  mysql-backup:
    driver: local

configs:
  mysql-config:
    file: ./mysql/custom.cnf
